// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StepChange.Blogger.DAL.Persistence;

namespace StepChange.Blogger.Web.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20220912074441_InitialWithTestData")]
    partial class InitialWithTestData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StepChange.Blogger.DAL.Models.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25d459fb-f3db-47f5-ab47-49526d88b4ad"),
                            Content = "As the curtains rise up on 2019, it’s time to look back at the amazing innovations that came out last year.We conducted over 400 hackathons with enterprises, universities, nonprofits, and governments in various fields, ranging from shaping the future of music to creating Fintech solutions",
                            CreationDate = new DateTime(2022, 9, 12, 16, 44, 41, 9, DateTimeKind.Local).AddTicks(9159),
                            ModificationDate = new DateTime(2022, 9, 12, 16, 44, 41, 9, DateTimeKind.Local).AddTicks(9392),
                            PublisherId = new Guid("afce8424-6086-43d0-8ac8-a088e2d97cec"),
                            Title = "Top 10 Hackathon Ideas 2018"
                        },
                        new
                        {
                            Id = new Guid("a447b7d4-22f4-4a41-8dba-623a67ca0f50"),
                            Content = "Whenever we are writing a headline we make sure that we use the keyword in the title. This helps us in matching the intent of the searcher. If our title can resonate with the searcher’s intent then there is a high chance of getting a higher CTR",
                            CreationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(133),
                            ModificationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(141),
                            PublisherId = new Guid("1adcf6fd-f3b7-4ac9-9763-f7471ed15a78"),
                            Title = "How to Choose the Best Blogging Platform in 2019"
                        },
                        new
                        {
                            Id = new Guid("b486a4d0-c9b3-49f9-b5ee-097815f9b16a"),
                            Content = "According to Osiris Parikh, the team at Counter Terrorism Group used a very gripping title to draw readers into the content, and also focused the piece on a very pressing issue in which many people are interested in.",
                            CreationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(173),
                            ModificationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(174),
                            PublisherId = new Guid("a7c00a98-0d0f-4e16-8a59-6c0977454456"),
                            Title = "The Prevalence and Danger of Copycat Attacks"
                        },
                        new
                        {
                            Id = new Guid("4a2c30dc-9584-4af3-ae77-93e7e58e0831"),
                            Content = "While doing keyword research we noticed that Microsoft teams vs Slack had around has 2.3K search volume, Md Mohsin Ansari explains.Once we determined the high intent keywords for our niche, we no longer had to follow the traditional inbound marketing pattern.",
                            CreationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(179),
                            ModificationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(180),
                            PublisherId = new Guid("a71e784b-09b7-4196-bd4b-e082ea49d420"),
                            Title = "Microsoft Teams Vs Slack"
                        },
                        new
                        {
                            Id = new Guid("c3b1e9dc-bf93-4ad1-88cf-a0280783e1c1"),
                            Content = "Next, it’s timely. No surprise, marketers and business leaders looking for insight into their social media strategy want the most up-to-date advice possible. Who wants to read recommendations on social media strategy from 2017? (Many competitors still talk about Google Plus, yikes.)",
                            CreationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(185),
                            ModificationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(186),
                            PublisherId = new Guid("24e4a91d-8f57-4ef1-8948-9b7bbeef471a"),
                            Title = "The Proven 2019 Social Media Strategy Framework"
                        },
                        new
                        {
                            Id = new Guid("1a3ee5fb-d09b-4589-8da4-82d2d2d5728d"),
                            Content = "This title gets lots of clicks because it uses a proven formula that is working well on my site, says Marsha Kelly. Odd number (101) + Keyword (microblading business names) + modifier with highly emotional words (Your + New).",
                            CreationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(190),
                            ModificationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(191),
                            PublisherId = new Guid("9c265243-fa03-4ee1-90e9-1b97328490c1"),
                            Title = "101 Catchy Microblading Business Names"
                        },
                        new
                        {
                            Id = new Guid("ac35bfe1-81e0-496a-96e9-f80662243c58"),
                            Content = "The pandemic brought forth ample shifts and disruptions in industries worldwide. And with that shift came the resurgence of QR Codes – a contactless solution that bridges the gap between physical and digital experiences",
                            CreationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(203),
                            ModificationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(204),
                            PublisherId = new Guid("376d27c5-9958-4ed1-8d2e-cc251e96cb1d"),
                            Title = "Do People Still Use QR Codes in 2019?"
                        },
                        new
                        {
                            Id = new Guid("513cb6bf-5e13-480a-8b23-1fe7d94b1d3d"),
                            Content = "While there are many gimmicks to posts with highest click-through rates this page performs not only as our highest CTR blog post but the second-best CTR on our entire site, writes Alex Kehoe",
                            CreationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(210),
                            ModificationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(211),
                            PublisherId = new Guid("afce8424-6086-43d0-8ac8-a088e2d97cec"),
                            Title = "How to Integrate Shopify With WordPress"
                        },
                        new
                        {
                            Id = new Guid("ba45ad21-8414-460d-b3ec-4d68f88fd671"),
                            Content = "So, why did it work? It’s because the author looked at the competition, as Sam Maizlech explains: “It comes down to what else was being offered on the market. Many similar sites would focus primarily on the guns and not the shooter which is where I saw an opening for viewership.”",
                            CreationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(216),
                            ModificationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(218),
                            PublisherId = new Guid("afce8424-6086-43d0-8ac8-a088e2d97cec"),
                            Title = "Size Matters: Guns and Body Types"
                        },
                        new
                        {
                            Id = new Guid("8d6360be-e99b-473a-9b51-4bfbf27210bc"),
                            Content = "We also noticed there are two different intent phrases most people use when searching for this type of information: “asking for referral” and “recommendation”. Writing a title can be simple as adding actionable words, but also using the phrases users use to search for their answers.",
                            CreationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(223),
                            ModificationDate = new DateTime(2022, 9, 12, 16, 44, 41, 10, DateTimeKind.Local).AddTicks(224),
                            PublisherId = new Guid("1adcf6fd-f3b7-4ac9-9763-f7471ed15a78"),
                            Title = "How to Write an Email Asking for a Referral"
                        });
                });

            modelBuilder.Entity("StepChange.Blogger.DAL.Models.BlogPublisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Publisher")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("BlogPublishers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("afce8424-6086-43d0-8ac8-a088e2d97cec"),
                            HashPassword = "m4dppKdClZotApjDb7cGI/LfrNqENiN98I2N/Vs3N0w=",
                            Publisher = "Nitin",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("1adcf6fd-f3b7-4ac9-9763-f7471ed15a78"),
                            HashPassword = "m4dppKdClZotApjDb7cGI/LfrNqENiN98I2N/Vs3N0w=",
                            Publisher = "Alonso",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("a7c00a98-0d0f-4e16-8a59-6c0977454456"),
                            HashPassword = "m4dppKdClZotApjDb7cGI/LfrNqENiN98I2N/Vs3N0w=",
                            Publisher = "Ojasvi",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("a71e784b-09b7-4196-bd4b-e082ea49d420"),
                            HashPassword = "m4dppKdClZotApjDb7cGI/LfrNqENiN98I2N/Vs3N0w=",
                            Publisher = "Mando",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("24e4a91d-8f57-4ef1-8948-9b7bbeef471a"),
                            HashPassword = "m4dppKdClZotApjDb7cGI/LfrNqENiN98I2N/Vs3N0w=",
                            Publisher = "Neo",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("9c265243-fa03-4ee1-90e9-1b97328490c1"),
                            HashPassword = "m4dppKdClZotApjDb7cGI/LfrNqENiN98I2N/Vs3N0w=",
                            Publisher = "Marcus",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("376d27c5-9958-4ed1-8d2e-cc251e96cb1d"),
                            HashPassword = "m4dppKdClZotApjDb7cGI/LfrNqENiN98I2N/Vs3N0w=",
                            Publisher = "Ed",
                            Role = 1
                        });
                });

            modelBuilder.Entity("StepChange.Blogger.DAL.Models.PublisherRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PublisherRoles");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Can create and edit all blog posts."
                        },
                        new
                        {
                            Id = 1,
                            Description = "Can create, edit and delete all blog posts."
                        });
                });

            modelBuilder.Entity("StepChange.Blogger.DAL.Models.BlogPost", b =>
                {
                    b.HasOne("StepChange.Blogger.DAL.Models.BlogPublisher", "BlogPublisher")
                        .WithMany("BlogPosts")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StepChange.Blogger.DAL.Models.BlogPublisher", b =>
                {
                    b.HasOne("StepChange.Blogger.DAL.Models.PublisherRole", "PublisherRole")
                        .WithMany("BlogPublishers")
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
